name: flutter_udemy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  retrofit: ^3.3.1
  analyzer:
  dio: ^4.0.6
  json_serializable: ^6.5.4
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.16
  device_info_plus: ^8.0.0
  freezed: ^2.3.2
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/hollow_circle_ic.svg
    - assets/images/solid_circle_ic.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/right_arrow_ic.svg



  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 300
